# @package _global_
model:
  name: DiffusionConcat
  stage: diffusion
  dim_input: 32
  dim_latent: 768
  dim_condition: 1024
  num_layers: 24
  nhead_divisor: 64
  feedforward_dim: 2048
  dropout: 0.1
  prediction_type: epsilon
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  variance_type: fixed_small
  autoencoder:
    name: AutoEncoder_1119_light
    weights: ???
  num_max_faces: 30
  pad_method: random
  stored_z: true
  use_mean: true
  train_decoder: false
  loss: l2
  is_aug: true
