name: Diffusion_dataset
raw_data_root: ???
train_dataset: ???
val_dataset: ???
test_dataset: ???
cached_latent_root: null
condition_data_root: null
condition_name: ${condition.condition_name}
cached_condition: ${condition.cached_features}
is_aug: false
is_overfit: true
load_topology: false
max_faces: ${model.padding.max_faces}
padding: ${model.padding.type}
num_points: 10000
epoch_scale_factor: 200
real_photo_ratio: 1.0
augmentation:
  enabled: true
  random_rotate: true
  random_scale: true
  scale_range: [0.9, 1.1]
