name: Dummy_dataset
length: 1000
raw_data_root: null
train_dataset: null
val_dataset: null
test_dataset: null
cached_latent_root: null
condition_data_root: null
condition_name: null
cached_condition: false
is_aug: false
is_overfit: false
load_topology: false
max_faces: ${model.padding.max_faces}
padding: ${model.padding.type}
num_points: 10000
epoch_scale_factor: 1
real_photo_ratio: 1.0
augmentation:
  enabled: false
  random_rotate: false
  random_scale: false
  scale_range: [1.0, 1.0]
