# @package _global_
strategy:
  name: KnowledgeDistillation
  teacher:
    checkpoint: ???
    freeze: true
  loss:
    kd_weight: 1.0
    diffusion_weight: 1.0
    align_weight: 0.5
    temperature: 1.0
