defaults:
  - trainer: default
  - dataset: diffusion
  - model: diffusion
  - condition: single_img

trainer:
  batch_size: 64
  learning_rate: 1.0e-4
  devices: 8
  exp_name: diffusion_topo_bias_real

dataset:
  name: Diffusion_dataset
  load_topology: true
  real_photo_ratio: 1.0
  scale_factor: 200

model:
  topology_bias:
    enabled: true
    scale: 2.0

eval:
  enabled: false
  output_dir: null
  num_samples: 100
  post_process: true

hydra:
  run:
    dir: ${trainer.output_dir}/${trainer.exp_name}
  job:
    chdir: false
